# Generated by Django 4.0.4 on 2022-05-19 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_bjpvote_saralbooth'),
    ]

    operations = [
        migrations.CreateModel(
            name='BjpVotes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('election_year', models.BigIntegerField(blank=True, null=True)),
                ('election_type', models.TextField(blank=True, null=True)),
                ('vote_ssecured_by_bjp', models.TextField(blank=True, null=True)),
                ('bjp_position', models.BigIntegerField(blank=True, null=True)),
                ('correction_in_vote_secured_by_bjp', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bjp_votes',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='BjpVote',
        ),
    ]
