# Generated by Django 4.0.4 on 2022-05-19 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_delete_bjpvote_delete_saralbooth'),
    ]

    operations = [
        migrations.CreateModel(
            name='BjpVotes',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('election_year', models.BigIntegerField(blank=True, null=True)),
                ('election_type', models.TextField(blank=True, null=True)),
                ('vote_ssecured_by_bjp', models.TextField(blank=True, null=True)),
                ('bjp_position', models.BigIntegerField(blank=True, null=True)),
                ('correction_in_vote_secured_by_bjp', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bjp_votes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SaralBooth',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('state', models.TextField(blank=True, null=True)),
                ('ac', models.BigIntegerField(blank=True, null=True)),
                ('ac_name', models.TextField(blank=True, null=True)),
                ('booth_number', models.BigIntegerField(blank=True, null=True)),
                ('booth_name', models.TextField(blank=True, null=True)),
                ('saral_state_id', models.BigIntegerField(blank=True, null=True)),
                ('saral_ac_id', models.BigIntegerField(blank=True, null=True)),
                ('current_voters', models.BigIntegerField(blank=True, null=True)),
                ('pm_targeted_votes', models.FloatField(blank=True, null=True)),
                ('cm_targeted_votes', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'saral_booth',
                'managed': False,
            },
        ),
    ]
