# Generated by Django 4.0.4 on 2022-06-08 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_bjpvotes_saralbooth'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ac',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('number', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ac',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'state',
                'managed': False,
            },
        ),
    ]
